# docker-compose.yml - с альтернативным образом
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: minecraft_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Xakin1310228
      MYSQL_DATABASE: minecraft_support
      MYSQL_USER: root
      MYSQL_PASSWORD: Xakin1310228
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: minecraft_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest  # или lscr.io/linuxserver/phpmyadmin:latest
    container_name: minecraft_phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT_NUMBER=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Xakin1310228
      - PHPMYADMIN_ALLOW_ARBITRARY_SERVER=yes
    ports:
      - "8080:8080"  # bitnami использует 8080, linuxserver - 80

  adminer:
    image: adminer:latest
    container_name: minecraft_adminer
    restart: always
    depends_on:
      - mysql
    ports:
      - "8081:8080"

volumes:
  mysql_data:
  redis_data: